### ISSUE TITLE
Can not find apk file

### ISSUE THREAD

**Issue by Raycokes2000** [jonkootje/toon-app#3]
Can not find apk file. There is no download link anywhere. Please fix an dput in readme

**Comment by jonkootje** [comment]
APK file can be found in the build directory: https://github.com/jonkootje/toon-app/tree/master/build

**Comment by jonkootje** [comment]
You can use the following link to download it to your android device: https://github.com/jonkootje/toon-app/raw/master/build/toon.apk

**Comment by Raycokes2000** [comment]
My mistake, thanks anyway 🤣😜👍👍👌

**Comment by jonkootje** [comment]
Let me know if the app still works properly if you are going to try it! Haven't touched it in ages and I'm curious.
